# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class ClipDialog(object):
    def __init__(self):
               
        self.min_area = 500
        self.alpha = 0.2
        self.threshold = (32, 255)
        self.width = 1000
        self.show_detection = False

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 581, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 19, 561, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.alphaEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphaEdit.sizePolicy().hasHeightForWidth())
        self.alphaEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.alphaEdit.setFont(font)
        self.alphaEdit.setObjectName("alphaEdit")
        self.gridLayout.addWidget(self.alphaEdit, 1, 1, 1, 1)
        self.minThreshEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minThreshEdit.sizePolicy().hasHeightForWidth())
        self.minThreshEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minThreshEdit.setFont(font)
        self.minThreshEdit.setObjectName("minThreshEdit")
        self.gridLayout.addWidget(self.minThreshEdit, 3, 1, 1, 1)
        self.maxThreshLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxThreshLabel.sizePolicy().hasHeightForWidth())
        self.maxThreshLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.maxThreshLabel.setFont(font)
        self.maxThreshLabel.setObjectName("maxThreshLabel")
        self.gridLayout.addWidget(self.maxThreshLabel, 4, 0, 1, 1)
        self.minThreshLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minThreshLabel.sizePolicy().hasHeightForWidth())
        self.minThreshLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minThreshLabel.setFont(font)
        self.minThreshLabel.setObjectName("minThreshLabel")
        self.gridLayout.addWidget(self.minThreshLabel, 3, 0, 1, 1)
        self.minAreaLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minAreaLabel.setFont(font)
        self.minAreaLabel.setObjectName("minAreaLabel")
        self.gridLayout.addWidget(self.minAreaLabel, 0, 0, 1, 1)
        self.processingWidthLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processingWidthLabel.sizePolicy().hasHeightForWidth())
        self.processingWidthLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.processingWidthLabel.setFont(font)
        self.processingWidthLabel.setObjectName("processingWidthLabel")
        self.gridLayout.addWidget(self.processingWidthLabel, 5, 0, 1, 1)
        self.minAreaEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.minAreaEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minAreaEdit.sizePolicy().hasHeightForWidth())
        self.minAreaEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minAreaEdit.setFont(font)
        self.minAreaEdit.setObjectName("minAreaEdit")
        self.gridLayout.addWidget(self.minAreaEdit, 0, 1, 1, 1)
        self.maxThreshEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxThreshEdit.sizePolicy().hasHeightForWidth())
        self.maxThreshEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxThreshEdit.setFont(font)
        self.maxThreshEdit.setObjectName("maxThreshEdit")
        self.gridLayout.addWidget(self.maxThreshEdit, 4, 1, 1, 1)
        self.processingWidthEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processingWidthEdit.sizePolicy().hasHeightForWidth())
        self.processingWidthEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.processingWidthEdit.setFont(font)
        self.processingWidthEdit.setObjectName("processingWidthEdit")
        self.gridLayout.addWidget(self.processingWidthEdit, 5, 1, 1, 1)
        self.alphaLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphaLabel.sizePolicy().hasHeightForWidth())
        self.alphaLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.alphaLabel.setFont(font)
        self.alphaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.alphaLabel.setObjectName("alphaLabel")
        self.gridLayout.addWidget(self.alphaLabel, 1, 0, 1, 1)
        self.showVideoCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.showVideoCheckBox.setGeometry(QtCore.QRect(10, 270, 600, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.showVideoCheckBox.setFont(font)
        self.showVideoCheckBox.setObjectName("showVideoCheckBox")
        self.startButton = QtWidgets.QPushButton(self.groupBox)
        self.startButton.setGeometry(QtCore.QRect(10, 340, 93, 31))
        self.startButton.setObjectName("startButton")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(110, 340, 471, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.infoLabel = QtWidgets.QLabel(self.groupBox)
        self.infoLabel.setEnabled(False)
        self.infoLabel.setGeometry(QtCore.QRect(9, 310, 561, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.infoLabel.setFont(font)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Clipper"))
        self.groupBox.setTitle(_translate("Dialog", "Set Parameters"))
        self.alphaEdit.setText(_translate("Dialog", str(self.alpha)))
        self.minThreshEdit.setText(_translate("Dialog", str(self.threshold[0])))
        self.maxThreshLabel.setText(_translate("Dialog", "Max threshold (max 255):"))
        self.minThreshLabel.setText(_translate("Dialog", "Min threshold (min 0):"))
        self.minAreaLabel.setText(_translate("Dialog", "Minimum area:"))
        self.processingWidthLabel.setText(_translate("Dialog", "Processing width (of resized frame):"))
        self.minAreaEdit.setText(_translate("Dialog", str(self.min_area)))
        self.maxThreshEdit.setText(_translate("Dialog", str(self.threshold[1])))
        self.processingWidthEdit.setText(_translate("Dialog", str(self.width)))
        self.alphaLabel.setText(_translate("Dialog", "Alpha (between 0 and 1):"))
        self.showVideoCheckBox.setText(_translate("Dialog", "Show detection video (processing can be a bit slower)"))
        self.startButton.setText(_translate("Dialog", "Start"))
        self.infoLabel.setText(_translate("Dialog", ""))

    def setParams(self):
        
        self.min_area = int(self.minAreaEdit.text())
        self.alpha = float(self.alphaEdit.text())
        minThresh = int(self.minThreshEdit.text())
        maxThresh = int(self.maxThreshEdit.text())
        self.threshold = (minThresh, maxThresh)
        self.width = int(self.processingWidthEdit.text())
        self.show_detection = self.showVideoCheckBox.isChecked()