# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt6 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(710, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 691, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 19, 671, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.processingWidthEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processingWidthEdit.sizePolicy().hasHeightForWidth())
        self.processingWidthEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.processingWidthEdit.setFont(font)
        self.processingWidthEdit.setObjectName("processingWidthEdit")
        self.gridLayout.addWidget(self.processingWidthEdit, 5, 1, 1, 1)
        self.alphaLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphaLabel.sizePolicy().hasHeightForWidth())
        self.alphaLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.alphaLabel.setFont(font)
        self.alphaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.alphaLabel.setObjectName("alphaLabel")
        self.gridLayout.addWidget(self.alphaLabel, 1, 0, 1, 1)
        self.processingWidthLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processingWidthLabel.sizePolicy().hasHeightForWidth())
        self.processingWidthLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.processingWidthLabel.setFont(font)
        self.processingWidthLabel.setObjectName("processingWidthLabel")
        self.gridLayout.addWidget(self.processingWidthLabel, 5, 0, 1, 1)
        self.minAreaLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minAreaLabel.setFont(font)
        self.minAreaLabel.setObjectName("minAreaLabel")
        self.gridLayout.addWidget(self.minAreaLabel, 0, 0, 1, 1)
        self.maxThreshEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxThreshEdit.sizePolicy().hasHeightForWidth())
        self.maxThreshEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxThreshEdit.setFont(font)
        self.maxThreshEdit.setObjectName("maxThreshEdit")
        self.gridLayout.addWidget(self.maxThreshEdit, 4, 1, 1, 1)
        self.minAreaEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.minAreaEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minAreaEdit.sizePolicy().hasHeightForWidth())
        self.minAreaEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minAreaEdit.setFont(font)
        self.minAreaEdit.setObjectName("minAreaEdit")
        self.gridLayout.addWidget(self.minAreaEdit, 0, 1, 1, 1)
        self.minThreshEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minThreshEdit.sizePolicy().hasHeightForWidth())
        self.minThreshEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minThreshEdit.setFont(font)
        self.minThreshEdit.setObjectName("minThreshEdit")
        self.gridLayout.addWidget(self.minThreshEdit, 3, 1, 1, 1)
        self.maxThreshLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxThreshLabel.sizePolicy().hasHeightForWidth())
        self.maxThreshLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.maxThreshLabel.setFont(font)
        self.maxThreshLabel.setObjectName("maxThreshLabel")
        self.gridLayout.addWidget(self.maxThreshLabel, 4, 0, 1, 1)
        self.alphaEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphaEdit.sizePolicy().hasHeightForWidth())
        self.alphaEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.alphaEdit.setFont(font)
        self.alphaEdit.setObjectName("alphaEdit")
        self.gridLayout.addWidget(self.alphaEdit, 1, 1, 1, 1)
        self.minThreshLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minThreshLabel.sizePolicy().hasHeightForWidth())
        self.minThreshLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minThreshLabel.setFont(font)
        self.minThreshLabel.setObjectName("minThreshLabel")
        self.gridLayout.addWidget(self.minThreshLabel, 3, 0, 1, 1)
        self.minMotionFramesEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minMotionFramesEdit.sizePolicy().hasHeightForWidth())
        self.minMotionFramesEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minMotionFramesEdit.setFont(font)
        self.minMotionFramesEdit.setObjectName("minMotionFramesEdit")
        self.gridLayout.addWidget(self.minMotionFramesEdit, 6, 1, 1, 1)
        self.minMotionFramesLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minMotionFramesLabel.sizePolicy().hasHeightForWidth())
        self.minMotionFramesLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minMotionFramesLabel.setFont(font)
        self.minMotionFramesLabel.setObjectName("minMotionFramesLabel")
        self.gridLayout.addWidget(self.minMotionFramesLabel, 6, 0, 1, 1)
        self.minNonMotionFramesLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minNonMotionFramesLabel.sizePolicy().hasHeightForWidth())
        self.minNonMotionFramesLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minNonMotionFramesLabel.setFont(font)
        self.minNonMotionFramesLabel.setObjectName("minNonMotionFramesLabel")
        self.gridLayout.addWidget(self.minNonMotionFramesLabel, 7, 0, 1, 1)
        self.minNonMotionFramesEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minNonMotionFramesEdit.sizePolicy().hasHeightForWidth())
        self.minNonMotionFramesEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minNonMotionFramesEdit.setFont(font)
        self.minNonMotionFramesEdit.setObjectName("minNonMotionFramesEdit")
        self.gridLayout.addWidget(self.minNonMotionFramesEdit, 7, 1, 1, 1)
        self.showVideoCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.showVideoCheckBox.setGeometry(QtCore.QRect(10, 360, 391, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.showVideoCheckBox.setFont(font)
        self.showVideoCheckBox.setObjectName("showVideoCheckBox")
        self.startButton = QtWidgets.QPushButton(self.groupBox)
        self.startButton.setGeometry(QtCore.QRect(10, 430, 93, 31))
        self.startButton.setObjectName("startButton")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(110, 430, 581, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.infoLabel = QtWidgets.QLabel(self.groupBox)
        self.infoLabel.setEnabled(False)
        self.infoLabel.setGeometry(QtCore.QRect(10, 400, 661, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.infoLabel.setFont(font)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Process"))
        self.groupBox.setTitle(_translate("Dialog", "Set Parameters"))
        self.processingWidthEdit.setText(_translate("Dialog", "1000"))
        self.alphaLabel.setText(_translate("Dialog", "Alpha:"))
        self.processingWidthLabel.setText(_translate("Dialog", "Processing width"))
        self.minAreaLabel.setText(_translate("Dialog", "Minimum area:"))
        self.maxThreshEdit.setText(_translate("Dialog", "255"))
        self.minAreaEdit.setText(_translate("Dialog", "500"))
        self.minThreshEdit.setText(_translate("Dialog", "32"))
        self.maxThreshLabel.setText(_translate("Dialog", "Max threshold:"))
        self.alphaEdit.setText(_translate("Dialog", "0.2"))
        self.minThreshLabel.setText(_translate("Dialog", "Min threshold:"))
        self.minMotionFramesEdit.setText(_translate("Dialog", "30"))
        self.minMotionFramesLabel.setText(_translate("Dialog", "Min motion frames"))
        self.minNonMotionFramesLabel.setText(_translate("Dialog", "Min non-motion frames"))
        self.minNonMotionFramesEdit.setText(_translate("Dialog", "30"))
        self.showVideoCheckBox.setText(_translate("Dialog", "Show detection video (processing will be slower)"))
        self.startButton.setText(_translate("Dialog", "Start"))
        self.infoLabel.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

