# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class ClipDialog(object):
    def __init__(self):
               
        self.min_area = 500
        self.alpha = 0.2
        self.threshold = (32, 255)
        self.width = 1000
        self.show_detection = False
        self.minMotionFrames = 30
        self.minNonMotionFrames = 30
        self.nonMotionBeforeStart = 2
        self.nonMotionAfter = 0
        self.minFramesToKeep = 24

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(710, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 691, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 19, 671, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.processingWidthEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processingWidthEdit.sizePolicy().hasHeightForWidth())
        self.processingWidthEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.processingWidthEdit.setFont(font)
        self.processingWidthEdit.setObjectName("processingWidthEdit")
        self.gridLayout.addWidget(self.processingWidthEdit, 3, 1, 1, 1)
               
        self.processingWidthLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processingWidthLabel.sizePolicy().hasHeightForWidth())
        self.processingWidthLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.processingWidthLabel.setFont(font)
        self.processingWidthLabel.setObjectName("processingWidthLabel")
        self.gridLayout.addWidget(self.processingWidthLabel, 3, 0, 1, 1)
        self.minAreaLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minAreaLabel.setFont(font)
        self.minAreaLabel.setObjectName("minAreaLabel")
        self.gridLayout.addWidget(self.minAreaLabel, 0, 0, 1, 1)
        self.maxThreshEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxThreshEdit.sizePolicy().hasHeightForWidth())
        self.maxThreshEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxThreshEdit.setFont(font)
        self.maxThreshEdit.setObjectName("maxThreshEdit")
        self.gridLayout.addWidget(self.maxThreshEdit, 2, 1, 1, 1)
        self.minAreaEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.minAreaEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minAreaEdit.sizePolicy().hasHeightForWidth())
        self.minAreaEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minAreaEdit.setFont(font)
        self.minAreaEdit.setObjectName("minAreaEdit")
        self.gridLayout.addWidget(self.minAreaEdit, 0, 1, 1, 1)
        self.minThreshEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minThreshEdit.sizePolicy().hasHeightForWidth())
        self.minThreshEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minThreshEdit.setFont(font)
        self.minThreshEdit.setObjectName("minThreshEdit")
        self.gridLayout.addWidget(self.minThreshEdit, 1, 1, 1, 1)
        self.maxThreshLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxThreshLabel.sizePolicy().hasHeightForWidth())
        self.maxThreshLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.maxThreshLabel.setFont(font)
        self.maxThreshLabel.setObjectName("maxThreshLabel")
        self.gridLayout.addWidget(self.maxThreshLabel, 2, 0, 1, 1)
        
        self.minThreshLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minThreshLabel.sizePolicy().hasHeightForWidth())
        self.minThreshLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minThreshLabel.setFont(font)
        self.minThreshLabel.setObjectName("minThreshLabel")
        self.gridLayout.addWidget(self.minThreshLabel, 1, 0, 1, 1)
        self.minMotionFramesEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minMotionFramesEdit.sizePolicy().hasHeightForWidth())
        self.minMotionFramesEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minMotionFramesEdit.setFont(font)
        self.minMotionFramesEdit.setObjectName("minMotionFramesEdit")
        self.gridLayout.addWidget(self.minMotionFramesEdit, 5, 1, 1, 1)
        self.minMotionFramesLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minMotionFramesLabel.sizePolicy().hasHeightForWidth())
        self.minMotionFramesLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minMotionFramesLabel.setFont(font)
        self.minMotionFramesLabel.setObjectName("minMotionFramesLabel")
        self.gridLayout.addWidget(self.minMotionFramesLabel, 5, 0, 1, 1)
        self.minNonMotionFramesLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minNonMotionFramesLabel.sizePolicy().hasHeightForWidth())
        self.minNonMotionFramesLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minNonMotionFramesLabel.setFont(font)
        self.minNonMotionFramesLabel.setObjectName("minNonMotionFramesLabel")
        self.gridLayout.addWidget(self.minNonMotionFramesLabel, 6, 0, 1, 1)
        self.minNonMotionFramesEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minNonMotionFramesEdit.sizePolicy().hasHeightForWidth())
        self.minNonMotionFramesEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minNonMotionFramesEdit.setFont(font)
        self.minNonMotionFramesEdit.setObjectName("minNonMotionFramesEdit")
        self.gridLayout.addWidget(self.minNonMotionFramesEdit, 6, 1, 1, 1)
        
        self.nonMotionBeforeStartLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nonMotionBeforeStartLabel.sizePolicy().hasHeightForWidth())
        self.nonMotionBeforeStartLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nonMotionBeforeStartLabel.setFont(font)
        self.nonMotionBeforeStartLabel.setObjectName("nonMotionBeforeStartLabel")
        self.gridLayout.addWidget(self.nonMotionBeforeStartLabel, 7, 0, 1, 1)

        self.nonMotionBeforeStartEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nonMotionBeforeStartEdit.sizePolicy().hasHeightForWidth())
        self.nonMotionBeforeStartEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nonMotionBeforeStartEdit.setFont(font)
        self.nonMotionBeforeStartEdit.setObjectName("minNonMotionFramesEdit")
        self.gridLayout.addWidget(self.nonMotionBeforeStartEdit, 7, 1, 1, 1)

        self.nonMotionAfterLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nonMotionAfterLabel.sizePolicy().hasHeightForWidth())
        self.nonMotionAfterLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nonMotionAfterLabel.setFont(font)
        self.nonMotionAfterLabel.setObjectName("nonMotionAfterLabel")
        self.gridLayout.addWidget(self.nonMotionAfterLabel, 8, 0, 1, 1)

        self.nonMotionAfterEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nonMotionAfterEdit.sizePolicy().hasHeightForWidth())
        self.nonMotionAfterEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.nonMotionAfterEdit.setFont(font)
        self.nonMotionAfterEdit.setObjectName("nonMotionAfterEdit")
        self.gridLayout.addWidget(self.nonMotionAfterEdit, 8, 1, 1, 1)

        self.minFramesToKeepLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minFramesToKeepLabel.sizePolicy().hasHeightForWidth())
        self.minFramesToKeepLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minFramesToKeepLabel.setFont(font)
        self.minFramesToKeepLabel.setObjectName("minFramesToKeepLabel")
        self.gridLayout.addWidget(self.minFramesToKeepLabel, 9, 0, 1, 1)
        
        self.minFramesToKeepEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minFramesToKeepEdit.sizePolicy().hasHeightForWidth())
        self.minFramesToKeepEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minFramesToKeepEdit.setFont(font)
        self.minFramesToKeepEdit.setObjectName("minFramesToKeepEdit")
        self.gridLayout.addWidget(self.minFramesToKeepEdit, 9, 1, 1, 1)

        self.alphaLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphaLabel.sizePolicy().hasHeightForWidth())
        self.alphaLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.alphaLabel.setFont(font)
        self.alphaLabel.setObjectName("alphaLabel")
        self.gridLayout.addWidget(self.alphaLabel, 10, 0, 1, 1)
        
        self.alphaEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphaEdit.sizePolicy().hasHeightForWidth())
        self.alphaEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.alphaEdit.setFont(font)
        self.alphaEdit.setObjectName("alphaEdit")
        self.gridLayout.addWidget(self.alphaEdit, 10, 1, 1, 1)
        
        
        self.showVideoCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.showVideoCheckBox.setGeometry(QtCore.QRect(10, 360, 600, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.showVideoCheckBox.setFont(font)
        self.showVideoCheckBox.setObjectName("showVideoCheckBox")
        self.startButton = QtWidgets.QPushButton(self.groupBox)
        self.startButton.setGeometry(QtCore.QRect(10, 430, 93, 31))
        self.startButton.setObjectName("startButton")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(110, 430, 581, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.infoLabel = QtWidgets.QLabel(self.groupBox)
        self.infoLabel.setEnabled(False)
        self.infoLabel.setGeometry(QtCore.QRect(10, 400, 661, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.infoLabel.setFont(font)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Clipper"))
        self.groupBox.setTitle(_translate("Dialog", "Set Parameters"))

        self.minThreshEdit.setText(_translate("Dialog", str(self.threshold[0])))
        self.maxThreshLabel.setText(_translate("Dialog", "Max Movement Threshold (0-255):"))
        self.minThreshLabel.setText(_translate("Dialog", "Min Movement Threshold (0-255):"))
        self.minAreaLabel.setText(_translate("Dialog", "Minimum Motion Area:"))
        self.processingWidthLabel.setText(_translate("Dialog", "Processing Width (zero = no frame resizing):"))
        self.minAreaEdit.setText(_translate("Dialog", str(self.min_area)))
        self.maxThreshEdit.setText(_translate("Dialog", str(self.threshold[1])))
        self.processingWidthEdit.setText(_translate("Dialog", str(self.width)))

        self.showVideoCheckBox.setText(_translate("Dialog", "Show detection video (processing can be a bit slower)"))
        self.startButton.setText(_translate("Dialog", "Start"))
        self.infoLabel.setText(_translate("Dialog", ""))
        self.minMotionFramesEdit.setText(_translate("Dialog", str(self.minMotionFrames)))
        self.minMotionFramesLabel.setText(_translate("Dialog", "Motion Refresh Interval"))
        self.minNonMotionFramesLabel.setText(_translate("Dialog", "Non-Motion Refresh Interval"))
        self.minNonMotionFramesEdit.setText(_translate("Dialog", str(self.minNonMotionFrames)))
        self.nonMotionBeforeStartLabel.setText(_translate("Dialog", "Non-Motion Starting Frame Buffer"))
        self.nonMotionBeforeStartEdit.setText(_translate("Dialog", str(self.nonMotionBeforeStart)))

        self.nonMotionAfterLabel.setText(_translate("Dialog", "Non-Motion Ending Frame Buffer"))
        self.nonMotionAfterEdit.setText(_translate("Dialog", str(self.nonMotionAfter)))

        self.minFramesToKeepLabel.setText(_translate("Dialog", "Min Frames Clipped"))
        self.minFramesToKeepEdit.setText(_translate("Dialog", str(self.minFramesToKeep)))

        self.alphaLabel.setText(_translate("Dialog", "Alpha"))
        self.alphaEdit.setText(_translate("Dialog", str(self.alpha)))

    def setParams(self):
        
        self.min_area = int(self.minAreaEdit.text())

        minThresh = int(self.minThreshEdit.text())
        maxThresh = int(self.maxThreshEdit.text())
        self.threshold = (minThresh, maxThresh)
        self.width = int(self.processingWidthEdit.text())
        self.show_detection = self.showVideoCheckBox.isChecked()
        self.minMotionFrames = int(self.minMotionFramesEdit.text())
        self.minNonMotionFrames = int(self.minNonMotionFramesEdit.text())
        self.nonMotionBeforeStart = int(self.nonMotionBeforeStartEdit.text())
        self.nonMotionAfter = int(self.nonMotionAfterEdit.text())
        self.minFramesToKeep = int(self.minFramesToKeepEdit.text())
        self.alpha = float(self.alphaEdit.text())
        
        if self.minMotionFrames < 1:
            self.minMotionFrames = 1
            
        if self.minNonMotionFrames < 1:
            self.minNonMotionFrames = 1
            
        